coderabbit.yaml# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  path_filters:
  - "!**/.xml"
  path_instructions:
  - path: "stackfrontend/app/**/*.tsx"
    instructions: |
      "nextjs code review "
  - path: "stackfrontend/components/**/*.tsx"
    instructions: |
      "UI Elements sit here"
  - path: "stackfrontend/app/api/*.ts"
    instructions: |
      "nextjs backend lives here "
  auto_review:
    enabled: true
    ignore_title_keywords:
    - "WIP"
    drafts: true
    base_branches:
    - "develop"
    - "feature/*"
chat:
  auto_reply: true
