id: daily_newsletter
namespace: company.team

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: daily-newsletter

inputs:
  - id: platforms
    type: ARRAY
    itemType: STRING
    defaults: ["dev.to", "hackernews", "techcrunch"]

  - id: creators
    type: ARRAY
    itemType: STRING
    required: false
  - id: tone
    type: STRING
    required: false

  - id: name
    type: STRING
    required: true

  - id: intrests
    type: ARRAY
    itemType: STRING
    required: true

  - id: email
    type: STRING
    required: true

tasks:
  - id: fetch_platforms
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: dev_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'dev.to' }}"
        then:
          - id: fetch_devto
            type: io.kestra.plugin.core.http.Request
            uri: https://dev.to/api/articles?top=7&per_page=5

      - id: hn_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'hackernews' }}"
        then:
          - id: fetch_hn_ids
            type: io.kestra.plugin.core.http.Request
            uri: https://hacker-news.firebaseio.com/v0/topstories.json

          - id: fetch_hn_items
            type: io.kestra.plugin.scripts.node.Script
            inputFiles:
              ids.json: "{{ outputs.fetch_hn_ids.body }}"
            beforeCommands:
              - npm install node-fetch@2
            outputFiles:
              - hn.txt
            script: |
              const fs = require("fs");
              const fetch = require("node-fetch");
              const ids = JSON.parse(fs.readFileSync("ids.json"));
              const top = ids.slice(0, 5);

              (async () => {
                const items = await Promise.all(
                  top.map(id =>
                    fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`)
                      .then(r => r.json())
                  )
                );
                fs.writeFileSync("hn.txt", JSON.stringify(items, null, 2));
              })();

      - id: techcrunch_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'techcrunch' }}"
        then:
          - id: fetch_techcrunch
            type: io.kestra.plugin.core.http.Request
            uri: https://techcrunch.com/feed/

  - id: ai_clean_parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: clean_devto_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'dev.to' }}"
        then:
          - id: ai_clean_devto
            type: io.kestra.plugin.ai.agent.AIAgent
            systemMessage: |
              You are a content curator for a tech newsletter.
              Extract relevant articles about systems engineering, AI, machine learning.
              Format: "Title: [title]\nDescription: [desc]\nURL: [url]\n\n"
            prompt: |
              Filter these Dev.to articles for systems engineering and AI content:
              {{ outputs.fetch_devto.body | jq('.') }}
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: google/gemini-2.5-flash-preview-09-2025

      - id: clean_hn_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'hackernews' }}"
        then:
          - id: ai_clean_hn
            type: io.kestra.plugin.ai.agent.AIAgent
            systemMessage: |
              You are a content curator.
              Extract relevant HackerNews stories about systems engineering and AI.
              Format: "Title: [title]\nURL: [url]\nScore: [score]\n\n"
            prompt: |
              Filter these HackerNews stories for systems engineering and AI:
              {{ read(outputs.fetch_hn_items.outputFiles['hn.txt']) }}
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: google/gemini-2.5-flash-preview-09-2025

      - id: clean_techcrunch_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'techcrunch' }}"
        then:
          - id: parse_techcrunch
            type: io.kestra.plugin.scripts.python.Script
            docker:
              image: python:3.11-slim
            beforeCommands:
              - pip install feedparser
            outputFiles:
              - techcrunch_raw.txt
            script: |
              import feedparser
              import json

              rss_content = '''{{ outputs.fetch_techcrunch.body }}'''
              feed = feedparser.parse(rss_content)

              articles = []
              for entry in feed.entries[:10]:
                  articles.append({
                      'title': entry.get('title', 'N/A'),
                      'summary': entry.get('summary', 'N/A'),
                      'link': entry.get('link', 'N/A')
                  })

              with open('techcrunch_raw.txt', 'w') as f:
                  f.write(json.dumps(articles, indent=2))

          - id: ai_clean_techcrunch
            type: io.kestra.plugin.ai.agent.AIAgent
            systemMessage: |
              You are a content curator.
              Extract TechCrunch articles about AI and infrastructure.
              Format: "Title: [title]\nDescription: [desc]\nURL: [url]\n\n"
            prompt: |
              Filter these TechCrunch articles for AI and systems engineering:
              {{ read(outputs.parse_techcrunch.outputFiles['techcrunch_raw.txt']) }}
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: google/gemini-2.5-flash-preview-09-2025

  - id: ingest_all
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: ingest_devto_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'dev.to' }}"
        then:
          - id: ingest_devto
            type: io.kestra.plugin.ai.rag.IngestDocument
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: "openai/text-embedding-3-small"
            embeddings:
              type: io.kestra.plugin.ai.embeddings.KestraKVStore
              kvName: "newsletter-embeddings"
            fromDocuments:
              - content: "{{ outputs.ai_clean_devto.textOutput }}"
                metadata:
                  source: dev.to

      - id: ingest_hn_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'hackernews' }}"
        then:
          - id: ingest_hn
            type: io.kestra.plugin.ai.rag.IngestDocument
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: "openai/text-embedding-3-small"
            embeddings:
              type: io.kestra.plugin.ai.embeddings.KestraKVStore
              kvName: "newsletter-embeddings"
            fromDocuments:
              - content: "{{ outputs.ai_clean_hn.textOutput }}"
                metadata:
                  source: hackernews

      - id: ingest_techcrunch_if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.platforms contains 'techcrunch' }}"
        then:
          - id: ingest_techcrunch
            type: io.kestra.plugin.ai.rag.IngestDocument
            provider:
              type: io.kestra.plugin.ai.provider.OpenRouter
              apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
              modelName: "openai/text-embedding-3-small"
            embeddings:
              type: io.kestra.plugin.ai.embeddings.KestraKVStore
              kvName: "newsletter-embeddings"
            fromDocuments:
              - content: "{{ outputs.ai_clean_techcrunch.textOutput }}"
                metadata:
                  source: techcrunch

  # - id: rag_summary
  #   type: io.kestra.plugin.ai.rag.ChatCompletion
  #   chatProvider:
  #     type: io.kestra.plugin.ai.provider.OpenRouter
  #     apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
  #     modelName: "anthropic/claude-3.5-sonnet"
  #   embeddingProvider:
  #     type: io.kestra.plugin.ai.provider.OpenRouter
  #     apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
  #     modelName: "openai/text-embedding-3-small"
  #   embeddings:
  #     type: io.kestra.plugin.ai.embeddings.KestraKVStore
  #     kvName: "newsletter-embeddings"
  #   systemMessage: |
  #     Create a 150-word summary of today's top tech trends in HTML.
  #     Focus on systems engineering and AI.
  #   prompt: "What are the key developments today in systems engineering and AI?"

  - id: ai_summary
    type: io.kestra.plugin.ai.rag.ChatCompletion
    chatProvider:
      type: io.kestra.plugin.ai.provider.OpenRouter
      apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
      modelName: "anthropic/claude-3.5-sonnet"
    embeddingProvider:
      type: io.kestra.plugin.ai.provider.OpenRouter
      apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
      modelName: "openai/text-embedding-3-small"
    embeddings:
      type: io.kestra.plugin.ai.embeddings.KestraKVStore
      kvName: "newsletter-embeddings"
    systemMessage: |
      Create a 150-word summary of today's top tech trends in HTML.
      Focus on intrests relevent to {{inputs.intrests | join(', ')}}.
      KEEP the TONE {{inputs.tone}}
    prompt: "What are the key developments today in systems engineering and AI?"

  - id: ai_newsletter
    type: io.kestra.plugin.ai.agent.AIAgent
    systemMessage: |
      You are an expert tech editor.

      IMPORTANT RULES:
      - Output ONLY valid HTML
      - Use <h2>, <h3>, <p>, <ul>, <li>, <a href="...">
      - ALL article titles MUST be clickable links
      - DO NOT use Markdown

      Your job:
      - Use the cleaned/filtered content as guidance
      - But pull the actual URLs from the original data
      - Create a comprehensive newsletter with working links
    prompt: |
      Create a newsletter combining these sources:

      CLEANED CONTENT (use this to know WHAT to include):
      DEV.TO (filtered): {{ outputs.ai_clean_devto.textOutput | default('None') }}
      HACKER NEWS (filtered): {{ outputs.ai_clean_hn.textOutput | default('None') }}
      TECHCRUNCH (filtered): {{ outputs.ai_clean_techcrunch.textOutput | default('None') }}

      ORIGINAL DATA (use this to get the URLs):
      DEV.TO (with URLs):
      {{ outputs.fetch_devto.body | default('[]') | jq('[.[] | {title: .title, url: .url, description: .description, tags: .tags}]') }}

      HACKER NEWS (with URLs):
      {{ outputs.fetch_hn_items is defined ? read(outputs.fetch_hn_items.outputFiles['hn.txt']) : 'No content' }}

      TECHCRUNCH (with URLs):
      {{ outputs.parse_techcrunch is defined ? read(outputs.parse_techcrunch.outputFiles['techcrunch_raw.txt']) : 'No content' }}

      Match articles from cleaned content with original data to get URLs.
      Format: <h3><a href="[URL]">[Title]</a></h3><p>[Description]</p>
    provider:
      type: io.kestra.plugin.ai.provider.OpenRouter
      apiKey: "{{ kv('OPEN_ROUTER_API_KEY') }}"
      modelName: google/gemini-2.5-flash-preview-09-2025

  - id: send_email
    type: io.kestra.plugin.notifications.mail.MailSend
    from: rhithesh1947@gmail.com
    to: "{{ inputs.email }}"
    username: "{{ kv('SMTP_USER') }}"
    password: "{{ kv('SMTP_PASS') }}"
    host: smtp.gmail.com
    port: 465
    subject: "Your Daily AI Newsletter BY SUBSTACK"
    htmlTextContent: |
      <h1>Hello {{inputs.name}}</h1>


        <p>
       {{outputs.ai_summary.textOutput}}
        <p>


       {{outputs.ai_newsletter.textOutput}}



        <hr />
        <p>Sent via Kestra</p>
